### ISSUE TITLE
ToDo : Webapp

### ISSUE THREAD

**Issue by satvikmaker** [prajjwaldimri/GithubXamarin#18]
List of To Do's:

- [x] Remove hard-coded images (prajjwaldimri to provide images)

- [ ] Replace all text (prajjwaldimri to provide text)

- [ ] Merge code from gh-pages to master (Plan a mechanism to keep code in-sync) (bozzmob)

- [ ] Notify Me feature

- [ ] Clean up code (bozzmob)

- [x] Logo (prajjwaldimri)

**Comment by satvikmaker** [comment]
#7 Commenting this, so as to keep reference.

**Comment by satvikmaker** [comment]
@prajjwaldimri I can complete most in the list with your help. Please address each item in the To-Do list.

**Comment by prajjwaldimri** [comment]
@bozzmob Logo files are here: https://github.com/prajjwaldimri/GithubUWP/tree/master/GithubUWP/Assets

**Comment by prajjwaldimri** [comment]
@bozzmob Any updates on this?
